version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    links:
      - cache
    volumes:
      - ./:/home/gradle/project
      - "~/.gradle:/home/gradle/.gradle"
    ports:
      - "8080:8080"
