version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    depends_on:
      - redis
    links:
      - redis
    environment:
      - "SPRING_REDIS_URL=redis://redis:6379"
    ports:
      - "8080:8080"
  redis:
    ports:
      - "7001:6379"